[package]
name = "tongfang-keyboard-control"
version = "1.0.0"
edition = "2021"

[dependencies]
nusb = "0.1.12"
futures-lite = "2.5.0"
clap = { version = "4.0", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26.4"
